import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "./contexts/ThemeProvider";

export const metadata: Metadata = {
  title: "Music app",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
          >
            {children}
          </ThemeProvider>
      </body>
    </html>
  );
}
